/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'nxf37731' at '11/30/17 1:44 PM' with Gradle 2.14.1
 *
 * @author nxf37731, @date 11/30/17 1:44 PM
 */
public class Library {
    public boolean someLibraryMethod() {
    	return true;
    }
    public static void main() {
    	System.out.println("******fourth gradle proj");
	}
}
